apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-tom
 namespace: otel
spec:
 ingressClassName: nginx
 rules:
 - host: "tomwang.sctp-sandbox.com"
   http:
     paths:
     - path: / # < play with this
       pathType: Prefix
       backend:
         service:
           name: otel-frontendproxy
           port:
             number: 8080